// export const translationEnglish={
// headers_manu:[
// {1:"Home"},
// {2:"About"},
// {3:"Solution"},
// {4:"Services"},
// {5:"Contact"}
// ],
// home_title:"Tech Analytica Limited",
// about:"ABOUT US",
// about_details:"Tech Analytica Limited is one of the most promising IT Services providers in Bangladesh dedicated to delivering complete IT solutions to its clients, whether they are start-up operations or large corporations. Our receptive approach makes us understand the stipulation in business and gives us the work force in meeting the necessity to accomplishing the goal.In addition to having our head office in Bangladesh, we also have our sales office in Canada and ascending toward becoming a paramount business house both locally and internationally. Reliability is our trademark and business relationship are our strength. The company’s high level of productivity and performance is supported by a group of motivated staff and demand structured hardware setup.To Tech Analytica Limited, sky is not the limit, thus we continually welcome new opportunities to fulfil the increasing demand in the IT industry worldwide.",
// our_vision:"Our Vision",
// solution:"SOLUTION",
// ecommerce:"E-Commerce",
// healthTech:"HealthTech",
// drmSolution:"DRM Solutions",
// security_and_Biometric:"Security & Biometric",
// iot:"IoT",
// mobileApp:"Mobile App(Ios & Android)",
// services:"SERVICES",
// software_Development:"Software Development",
// web_Development:"Web Development",
// system_Integration:"System Integration",
// iT_Support_and_Services:"IT Support & Services",
// aI_Driven_Development:"AI Driven Development",
// online_Marketing:"Online Marketing",
// privacy_protection:"PRIVACY PROTECTION",
// privacy_protection_details:"At Tech Analytica, we are fully committed to the ethical practice of intellectual property protection, and ensure to protect the assets of our clients through strict company policy and intellectual property protection acts including:",
// privacy_protection_key:[
//     {1:" Execution of a comprehensive non-disclosure agreement"},
//     {2:" Signing of non-disclosure agreement on patent of intellectual property"},
//     {3:" Agreement to any ownership waiver agreements"},
//     {4:" Constant monitoring of employee activities in line with company policy"}
// ],
// contact:"CONTACT",
// location:"Location:",
// location_details:"Progress Tower, 4th floor, House #01, Road #23, Gulshan 1, Dhaka 1212",
// email:"Email",
// email_details:"info@techanalyticaltd.com",
// call:"Call",
// call_details1:"+880248811161",
// call_details2:"+880248811162",
// footer_title:"Tech Analytica Limited",
// member_of:"Member of",
// footer_details:"© Copyright Tech Analytica Limited (version 1.0) All Rights Reserved"
// };



// export const translationBangla={
// headers_manu:[
//         {1:"হোম"},
//         {2:"এবাউট"},
//         {3:"সল্যুশন"},
//         {4:"সার্ভিসেস"},
//         {5:"কন্টাক্ট"}
//         ],
// home_title:"টেক অ্যানালিটিকা লিমিটেড",
// about:"আমাদের সম্পর্কে",
// about_details:"টেক অ্যানালিটিকা লিমিটেড বাংলাদেশের অন্যতম প্রতিশ্রুতিশীল আইটি পরিষেবা প্রদানকারী যারা তার ক্লায়েন্টদের সম্পূর্ণ আইটি সমাধান সরবরাহ করতে নিবেদিত, সেগুলি স্টার্ট আপ অপারেশন বা বড় কর্পোরেশনই হোক না কেন। আমাদের গ্রহণযোগ্য দৃষ্টিভঙ্গি আমাদের ব্যবসার শর্তাবলী বুঝতে সাহায্য করে এবং লক্ষ্য অর্জনের প্রয়োজনীয়তা পূরণে আমাদের কর্মশক্তি দেয়। বাংলাদেশে আমাদের প্রধান কার্যালয় থাকার পাশাপাশি, কানাডায় আমাদের বিক্রয় অফিসও রয়েছে এবং একটি সর্বশ্রেষ্ঠ ব্যবসায় পরিণত হওয়ার দিকে এগিয়ে যাচ্ছি। উভয় স্থানীয় এবং আন্তর্জাতিকভাবে ঘর. নির্ভরযোগ্যতা আমাদের ট্রেডমার্ক এবং ব্যবসায়িক সম্পর্ক আমাদের শক্তি। কোম্পানির উচ্চ স্তরের উৎপাদনশীলতা এবং কর্মক্ষমতা একদল অনুপ্রাণিত কর্মী এবং চাহিদা স্ট্রাকচার্ড হার্ডওয়্যার সেটআপ দ্বারা সমর্থিত। টেক অ্যানালিটিকা লিমিটেডের কাছে, আকাশের সীমা নেই, এইভাবে আমরা বিশ্বব্যাপী আইটি শিল্পে ক্রমবর্ধমান চাহিদা পূরণের জন্য নতুন সুযোগগুলিকে ক্রমাগত স্বাগত জানাই।",
// our_vision:"আমাদের দৃষ্টি",
// solution:"সমাধান",
// ecommerce:"ই-কমার্স",
// healthTech:"হেলথটেক",
// drmSolution:"ডিআরএম সলিউশন",
// security_and_Biometric:"নিরাপত্তা এবং বায়োমেট্রিক",
// iot:"আইওটি",
// mobileApp:"মোবাইল অ্যাপ (আইওএস এবং অ্যান্ড্রয়েড)",
// services:"সেবা",
// software_Development:"সফটওয়্যার ডেভেলপমেন্ট",
// web_Development:"ওয়েব ডেভেলপমেন্ট",
// system_Integration:"সিস্টেম ইন্টিগ্রেশন",
// iT_Support_and_Services:"আইটি সাপোর্ট & সার্ভিসেস",
// aI_Driven_Development:"এআই ড্রিভেন ডেভেলপমেন্ট",
// online_Marketing:"অনলাইন মার্কেটিং",
// privacy_protection:"বাক্তিগত তথ্য সুরক্ষা",
// privacy_protection_details:"টেক অ্যানালিটিকায়, আমরা মেধা সম্পত্তি সুরক্ষার নৈতিক অনুশীলনের প্রতি সম্পূর্ণরূপে প্রতিশ্রুতিবদ্ধ, এবং কঠোর কোম্পানির নীতি এবং মেধা সম্পত্তি সুরক্ষা আইন সহ আমাদের ক্লায়েন্টদের সম্পদ সুরক্ষা নিশ্চিত করি:",
// privacy_protection_key:[
//     {1:" একটি ব্যাপক নন-ডিসক্লোজার চুক্তি সম্পাদন"},
//     {2:"মেধা সম্পত্তির পেটেন্টের উপর অ-প্রকাশ চুক্তি স্বাক্ষর করা"},
//     {3:" কোনো মালিকানা মওকুফ চুক্তিতে চুক্তি"},
//     {4:" কোম্পানির নীতির সাথে সঙ্গতিপূর্ণ কর্মচারী কার্যকলাপের অবিরাম পর্যবেক্ষণ"}
// ],
// contact:"যোগাযোগ",
// location:"অবস্থান",
// location_details:"প্রগ্রেস টাওয়ার, ৪র্থ তলা, বাড়ি #01, রোড #23, গুলশান 1, ঢাকা 1212",
// email:"ইমেইল",
// email_details:"info@techanalyticaltd.com",
// call:"কল",
// call_details1:"+880248811161",
// call_details2:"+880248811162",
// footer_title:"টেক অ্যানালিটিকা লিমিটেড",
// member_of:"এর সদস্য",
// footer_details:"©কপিরাইট টেক অ্যানালিটিকা লিমিটেড (সংস্করণ 1.0) সর্বস্বত্ব সংরক্ষিত৷"
// };
